package ubadbtools.recoveryLogAnalyzer.gui.forms;

import java.awt.Frame;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import ubadbtools.recoveryLogAnalyzer.common.RecoveryLog;

@SuppressWarnings("serial")
public class AnalyzeLogDialog extends JDialog
{
	//[start] Constructor
    public AnalyzeLogDialog(Frame parent, boolean modal, RecoveryLog log)
    {
    	super(parent, modal);
        initComponents();
        
        // Analizo cada aspecto del log
        AnalyzeValidity(log);
        AnalyzeRecoverability(log);
    }
    //[end]
    
    //[start] showDialog
    public static void showDialog(Frame parent, RecoveryLog log)
    {
    	AnalyzeLogDialog dialog = new AnalyzeLogDialog(parent, true, log);
        dialog.setVisible(true);
    }
    //[end]
    
    //[start] AnalyzeValidity
    public void AnalyzeValidity(RecoveryLog log)
    {
        //TODO: Completar
    }
    //[end]

    //[start] AnalyzeRecoverability
    public void AnalyzeRecoverability(RecoveryLog log)
    {
        //TODO: Completar
    }
    //[end]

    //[start] ShowErrorMessage
	/**
     * Muestra un mensaje de error al usuario
     * @param message
     */
	public void ShowErrorMessage(String message)
	{
		JOptionPane.showConfirmDialog(
			this,
			message,
			"Error",
			JOptionPane.DEFAULT_OPTION,
			JOptionPane.ERROR_MESSAGE);
	}
	//[end]
	
    //[start] InitComponents (AUTO-GENERATED)
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butCerrar = new javax.swing.JButton();

        setTitle("Análisis de log");

        butCerrar.setText("Cerrar");
        butCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(butCerrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(442, Short.MAX_VALUE)
                .addComponent(butCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	//[end]
    
    //[start] Eventos
    private void butCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCerrarMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_butCerrarMouseClicked
	//[end]
	
	//[start] Variables Form (AUTO-GENERATED)
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCerrar;
    // End of variables declaration//GEN-END:variables
    //[end]
}
